inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-active_encode.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/file_set_spec.rb'
    - 'spec/services/active_encode_derivative_service_spec.rb'
    - 'spec/services/derivative_service_spec.rb'
    - 'spec/services/option_service_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/services/option_service_spec.rb'
