inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-active_encode.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/hyrax/active_encode_encode_records_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/hyrax/active_encode_encode_records_controller.rb'
    - 'spec/controllers/hyrax/active_encode_encode_records_controller_spec.rb'
    - 'spec/rails_helper.rb'
    - 'spec/models/file_set_spec.rb'
    - 'spec/models/watched_encode_spec.rb'
    - 'spec/services/active_encode_derivative_service_spec.rb'
    - 'spec/services/derivative_service_spec.rb'
    - 'spec/services/default_option_service_spec.rb'
    - 'spec/services/persist_active_encode_derivatives_spec.rb'

Metrics/LineLength:
  Exclude:
  - 'spec/factories/hyrax/active_encode_encode_records.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/hyrax/active_encode_encode_records_controller_spec.rb'
    - 'spec/services/default_option_service_spec.rb'
    - 'spec/models/watched_encode_spec.rb'
    - 'spec/views/hyrax/active_encode_encode_records/index.html.erb_spec.rb'

Style/ClassVars:
  Exclude:
    - 'app/services/hyrax/active_encode/active_encode_derivative_service.rb'
